### PR TITLE
Fix unicycle 2d alignment

### PR DESCRIPTION
**Pull request by efernandez**
This requires https://github.com/locusrobotics/fuse/pull/62

Align `unicycle_2d::Model` and `StateKinematicConstraint` by:

1. Adding `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` to `StateKinematicConstraint`, because it has a `Matrix8d` attribute, which is a fixed-sized vectorizable type, since its size is a multiple of 16 bytes.

   See https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html

2. Using allocate_aligned_shared instead of make_shared to create an `std::shared_ptr` to `StateKinematicConstraint`, so the overloaded `operator new` is not ignored (`std::make_shared` doesn't use the overloaded one).

   See http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1049

### CODE REVIEW

**Comment by ayrton04** [comment]
Our build farm doesn't like this:

```
[2019-06-14T12:43:11.900Z] /home/xxxxxx/workspace/test_rosdistro_fuse_rl_PR-2/package/src/unicycle_2d/model.cpp: In member function ‘void fuse_rl::unicycle_2d::Model::generateMotionModel(const ros::Time&, const ros::Time&, std::vector<std::shared_ptr<fuse_core::Constraint> >&, std::vector<std::shared_ptr<fuse_core::Variable> >&)’:

[2019-06-14T12:43:11.900Z] /home/xxxxxx/workspace/test_rosdistro_fuse_rl_PR-2/package/src/unicycle_2d/model.cpp:230:21: error: ‘allocate_aligned_shared’ is not a member of ‘fuse_rl::unicycle_2d::StateKinematicConstraint’

[2019-06-14T12:43:11.900Z]    auto constraint = fuse_rl::unicycle_2d::StateKinematicConstraint::allocate_aligned_shared(

[2019-06-14T12:43:11.900Z]                      ^

[2019-06-14T12:43:11.900Z] make[2]: *** [CMakeFiles/fuse_rl.dir/src/unicycle_2d/model.cpp.o] Error 1

[2019-06-14T12:43:11.900Z] make[2]: *** Waiting for unfinished jobs....

[2019-06-14T12:43:11.900Z] make[1]: *** [CMakeFiles/fuse_rl.dir/all] Error 2

[2019-06-14T12:43:11.900Z] make: *** [all] Error 2

[2019-06-14T12:43:11.900Z] ---

[2019-06-14T12:43:11.900Z] Failed   <<< fuse_rl	[ Exited with code 2 ]

[2019-06-14T12:43:11.900Z] 

[2019-06-14T12:43:11.900Z] Summary: 0 packages finished [25.3s]

[2019-06-14T12:43:11.900Z]   1 package failed: fuse_rl

[2019-06-14T12:43:11.900Z]   1 package had stderr output: fuse_rl

script returned exit code 2
```

**Comment by efernandez** [comment]
@ayrton04 As I mentioned in the description, this requires locusrobotics/fuse#62

**Comment by ayrton04** [comment]
Ah! Sorry, missed that. Thanks.

**Review by ayrton04 — APPROVED** [review]

**Comment by svwilliams** [comment]
I need to do some research and testing for this one. In addition to the `make_shared` called manually when a Sensor/MotionModel creates a constraint, the Sensor/MotionModel API also has a `clone()` method, which is generally implemented as `return std::make_unique<Derived>(this)`. It seems like that is also likely to cause problems.

**Comment by efernandez** [comment]
@svwilliams `std::make_unique` seems to actually call the overloaded `operator new`: https://wandbox.org/permlink/IWfy6ixz1m7AaaWI

This is because it simply calls the `operator new` for the template type `_Tp`:

https://github.com/gcc-mirror/gcc/blob/88098bd2ed7738e54a78efe58320b16756220750/libstdc%2B%2B-v3/include/bits/unique_ptr.h#L927-L930

On the other side, `std::make_shared` internally uses `std::allocate_shared` passing the `std::allocator` for the template type `_Tp`, which calls the global `operator new`, not the overloaded one:

https://github.com/gcc-mirror/gcc/blob/88098bd2ed7738e54a78efe58320b16756220750/libstdc%2B%2B-v3/include/bits/shared_ptr.h#L854-L861

TBH I don't know why this isn't an issue in your system. It clearly has to be with the fact that things are already aligned for you, but I don't think you can assume that in all systems. Eigen requires `128-bit` alignment (see explanation in https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html), which I don't think it's guarantee in `64-bit` architectures.

**Comment by efernandez** [comment]
@svwilliams @ayrton04 The flag that exposes this issue is `-mavx`, at least. That flag enables AVX vectorization.

# Flags that don't require this fix

`catkin config --cmake-args -DCMAKE_CXX_FLAGS="-g -O2 -std=c++11" -DCMAKE_C_FLAGS="-g -O2"`

# Flags that require this fix

`catkin config --cmake-args -DCMAKE_CXX_FLAGS="-g -O2 -mavx -std=c++11" -DCMAKE_C_FLAGS="-g -O2 -mavx"`

# Steps to reproduce

1. For each of the two configs above, run `catkin build` for the `fuse_rl` package.
2. Then run something like `rosrun fuse_optimizers fixed_lag_smoother_node` with a `fuse_rl` configuration that has a `unicycle_2d` motion model. I emailed you the launch and yaml files I used to test it, as well as a bag file.

With the configuration that has the `-mavx` flag you'll get this error if you don't apply the fix from this PR:
``` bash
fixed_lag_smoother_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 64; int MatrixOrArrayOptions = 1]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
```

These are the versions of the compiler and the libraries that might be important for this issue:
* gcc : `(Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010`
* libstd : `libstdc++-5-dev:amd64 5.5.0-12ubuntu1~16.04` (although I also have version 6 and 7 installed)
* eigen :  libeigen3-dev 3.3.4-3`

Could you share your versions and results, please?

**Comment by efernandez** [comment]
Closing as I've already done with the sister PR https://github.com/locusrobotics/fuse/pull/62 in `fuse`. In this case in favour of https://github.com/locusrobotics/fuse_rl/pull/8, which uses the new macros from https://github.com/locusrobotics/fuse/pull/65, submitted to `fuse`.

**Pull request closed without merging**
